# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    mkdir rumble
    docker run -v $(PWD)/rumble:/rumble mcr.microsoft.com/azure-cli az storage blob download-batch -d /rumble -s $(BLOB_CONTAINER) --pattern rumble/*
    mv scan.py rumble/scan.py; cd rumble; ./scan.py
  displayName: 'Run owasp amass to enumerate subdomains and update scopes'
  env:
    AZURE_STORAGE_CONNECTION_STRING: $(AZURE_STORAGE_CONNECTION_STRING)
    RUMBLE_API_TOKEN: $(RUMBLE_API_TOKEN)
