# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
  - script: |
      echo $(pwd)
      # Inject all env vars, mount workspace folder
      docker run -v $(pwd):/mnt/rumble --env-file <( env| cut -f1 -d= ) mcr.microsoft.com/azure-cli bash -c "cd /mnt/rumble; chmod +x scan.py; ./scan.py"
    displayName: 'Run owasp amass to enumerate subdomains and update scopes'
    env:
      AZURE_STORAGE_CONNECTION_STRING: $(AZURE_STORAGE_CONNECTION_STRING)
      RUMBLE_API_TOKEN: $(RUMBLE_API_TOKEN)
